spring:
  application:
    name: ccrpc-demo-consumer
server:
  port: 8000

ccrpc:
  zkserver: 127.0.0.1:2181

app:
  id: app1
  namespace: public
  env: dev
  retries: 2
  connect-timeout: 5000
  read-timeout: 5000

logging:
  level:
    root: info