spring:
  application:
    name: ccrpc-demo-consumer
server:
  port: 8000

ccrpc:
  app:
    id: app1
    namespace: public
    env: dev
  consumer:
    retries: 2
    gray-ratio: 33
    connect-timeout: 5000
    read-timeout: 1_000
    fault-limit: 10 # 30s 内10次错误则隔离
    half-open-initial-delay: 10000
    half-open-delay: 60000

ccconfig:
  app: demo-consumer
  env: dev
  ns: public
  server: http://localhost:9000

ccregistry:
  servers:
    - http://localhost:8787
    - http://localhost:8788
    - http://localhost:8789

logging:
  level:
    root: info
    cc.rpc: debug