server:
  port: 9000

## cconfig
ccconfig:
  app: demo-provider
  env: dev
  ns: public
  server: http://localhost:9000

## ccrpc
ccrpc:
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001
      tc: 200 # 流控

# ccregistry
ccregistry:
  servers:
    - http://localhost:8787
    - http://localhost:8788
    - http://localhost:8789

logging:
  level:
    root: info
